<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-realentity) on 2016-12-25 19:00:26.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Application\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Application\Entity\Calendar
 *
 * @ORM\Entity()
 * @ORM\Table(name="calendar")
 */
class Calendar extends Base\Calendar
{
    public function __construct()
    {
        parent::__construct();
    }

}