<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-realentity) on 2016-12-25 19:00:26.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Application\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Application\Entity\EventAdditive
 *
 * @ORM\Entity()
 * @ORM\Table(name="eventAdditive", indexes={@ORM\Index(name="fk_eventAdditive_event1_idx", columns={"event_id"})})
 */
class EventAdditive extends Base\EventAdditive
{
    public function __construct()
    {
        parent::__construct();
    }

}