<?php

$fieldset = $form->get('event');
$form->setAttribute('action', $this->url('event', array('action' => 'add')))
      ->prepare();

echo $this->form()->openTag($form);

echo $this->formRow($fieldset->get('heading'));
echo $this->formRow($fieldset->get('begin'));
echo $this->formRow($fieldset->get('end'));
echo $this->formRow($fieldset->get('website'));

echo $this->formHidden($form->get('csrf'));
echo $this->formElement($form->get('submit')); ?>

<a href="<?php echo $this->url('event'); ?>">Cancel</a>

<?php echo $this->form()->closeTag();