<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('InbaZ'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/vendor/fullcalendar-3.1.0/fullcalendar.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
                ->prependFile($this->basePath() . '/js/custom.js')
                ->prependFile($this->basePath() . '/vendor/fullcalendar-3.1.0/fullcalendar.min.js')
                ->prependFile($this->basePath() . '/vendor/moment/moment-with-locales.min.js')
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>" title="Immer noch besser als Zaubern">
                        <?php echo $this->translate('InbaZ') ?>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <?php 
                    $partial = array('partial/main-nav.phtml', 'main_nav');
                    $this->navigation()
                            ->menu('main_nav')
                            ->setPartial($partial);
                    echo $this->navigation()
                            ->menu('main_nav')
                            ->render(); 
                    ?>

                    <?php 
                    $right_partial = array('partial/main-right-nav.phtml', 'top_nav');
                    $this->navigation()
                            ->menu('top_nav')
                            ->setPartial($right_partial);
                    echo $this->navigation()
                            ->menu('top_nav')
                            ->render(); 
                    ?>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <?php if(!empty($this->fluid) && $this->fluid): ?>
            <div class="container-fluid">
        <?php else: ?>    
            <div class="container">
        <?php endif; ?>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2012 - <?php echo date('Y') ?> by Andi Nitsche <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
