<h1>Convention Kalender</h1>
<div class="row">
    <div class="col-md-6">
        <p>Jeder mit einem Account hat die Möglichkeiten Conventions in diesen Kalender einzutragen. 
            Nach der Eintragung sind die Conventions auf der Warteliste und können 
            von anderen Jongleuren und Artisten freigeschaltet werden.</p>
        <p>Noch keinen Benutzeraccount? Hier geht's <a href="#">zur Anmeldung</a></p>
        <p><a class="btn btn-primary" href="<?php echo $this->url('event', array('action' => 'add')); ?>">Convention eintragen</a></p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div id="fullcalendar">
        </div>
    </div>
</div>