<h1 class="page-header">Convention Kalender</h1>
<!--<div class="row">
    <div class="col-md-6">
        <p>Jeder mit einem Account hat die Möglichkeiten Conventions in diesen Kalender einzutragen. 
            Nach der Eintragung sind die Conventions auf der Warteliste und können 
            von anderen Jongleuren und Artisten freigeschaltet werden.</p>
        <p>Noch keinen Benutzeraccount? Hier geht's <a href="#">zur Anmeldung</a></p>
        <p><a class="btn btn-lg btn-primary" href="<?php echo $this->url('event', array('action' => 'add')); ?>">neue Convention eintragen</a></p>
    </div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-body">
                <h4>Logo Contest</h4>
                <p>InbaZ braucht ein neues Logo und du kannst es erstellen.</p>
                <p><a href="#">mehr...</a></p>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <h4>Neue Convention</h4>
                <p>MünchenCon 2018 wurde eingetragen</p>
                <p><a href="#">mehr...</a></p>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <h4>Neue Convention</h4>
                <p>Karlsruhe Akro Con 2017 wurde eingetragen</p>
                <p><a href="#">mehr...</a></p>
            </div>
        </div>
    </div>
</div>-->

<div class="row">
    <div class="col-md-12">
        <p class="text-right"><a class="btn btn-primary" href="<?php echo $this->url('event', array('action' => 'add')); ?>">neue Convention eintragen</a></p>
        <div id="fullcalendar">
        </div>
    </div>
</div>